// Curated staple foods, per 100 g (or 100 ml for drinks).
//
// Values are standard reference values (USDA FoodData Central / IFCT 2017 / common
// Indian product labels), rounded. Carbohydrate is total carbohydrate (includes fiber),
// which is the convention on most nutrition labels.
//
// Each row: [id, name, category, unit, kcal, protein, carbs, fat, fiber, portions, aliases]
//   unit      'g' or 'ml' — the base serving is always 100 of this unit
//   portions  [[label, grams-or-ml], ...] household measures; the FIRST one is the default
//   aliases   extra search terms (Hindi names, spellings, English synonyms)

export const CORE_FOODS = [
  // ── Grains, breads & cereals ────────────────────────────────────────────
  ['rice-white-cooked', 'Rice, white, cooked (boiled)', 'Grains & breads', 'g', 130, 2.7, 28.2, 0.3, 0.4,
    [['1 katori (bowl)', 150], ['1 cup', 158], ['1 plate', 250]], ['rice', 'chawal', 'bhaat', 'plain rice', 'steamed rice', 'basmati rice', 'boiled rice']],
  ['rice-brown-cooked', 'Rice, brown, cooked', 'Grains & breads', 'g', 123, 2.7, 25.6, 1.0, 1.6,
    [['1 katori (bowl)', 150], ['1 cup', 195]], ['brown chawal']],
  ['roti', 'Roti / Chapati (whole wheat, no ghee)', 'Grains & breads', 'g', 280, 9.0, 52.7, 3.7, 8.4,
    [['1 medium roti', 40], ['1 small roti / phulka', 30], ['1 large roti', 55]], ['chapati', 'chapatti', 'phulka', 'fulka', 'rotli', 'wheat roti', 'atta roti']],
  ['naan', 'Naan, plain', 'Grains & breads', 'g', 290, 9.0, 50.0, 5.8, 2.2,
    [['1 naan', 90]], ['nan', 'tandoori naan']],
  ['bread-white', 'Bread, white', 'Grains & breads', 'g', 266, 8.9, 49.2, 3.3, 2.7,
    [['1 slice', 25]], ['white bread', 'sandwich bread', 'pav', 'bread']],
  ['bread-brown', 'Bread, whole wheat / brown', 'Grains & breads', 'g', 252, 12.4, 42.7, 3.5, 6.0,
    [['1 slice', 28]], ['brown bread', 'atta bread', 'multigrain bread']],
  ['oats-dry', 'Oats, rolled (dry)', 'Grains & breads', 'g', 379, 13.2, 67.7, 6.5, 10.1,
    [['1/2 cup', 40], ['1 tbsp', 5]], ['oatmeal dry', 'rolled oats', 'jai']],
  ['oats-cooked-water', 'Oatmeal / porridge, cooked with water', 'Grains & breads', 'g', 71, 2.5, 12.0, 1.5, 1.7,
    [['1 bowl', 234]], ['oats porridge', 'daliya oats']],
  ['cornflakes', 'Cornflakes (dry)', 'Grains & breads', 'g', 358, 7.5, 81.0, 0.4, 3.3,
    [['1 cup', 30]], ['corn flakes', 'cereal']],
  ['pasta-cooked', 'Pasta, cooked', 'Grains & breads', 'g', 158, 5.8, 30.9, 0.9, 1.8,
    [['1 cup', 140]], ['spaghetti', 'macaroni', 'penne']],
  ['quinoa-cooked', 'Quinoa, cooked', 'Grains & breads', 'g', 120, 4.4, 21.3, 1.9, 2.8,
    [['1 cup', 185]], []],
  ['instant-noodles-dry', 'Instant noodles, masala (dry weight)', 'Grains & breads', 'g', 433, 9.0, 61.0, 17.0, 2.0,
    [['1 packet', 70]], ['maggi', 'noodles', 'ramen']],
  ['poha-cooked', 'Poha, cooked (tempered)', 'Grains & breads', 'g', 180, 3.5, 30.0, 5.0, 1.5,
    [['1 plate', 200], ['1 katori (bowl)', 120]], ['pohe', 'aval', 'flattened rice', 'chivda poha', 'kanda poha']],
  ['dosa-plain', 'Dosa, plain', 'Grains & breads', 'g', 168, 4.0, 29.0, 3.9, 1.5,
    [['1 medium dosa', 75], ['1 large dosa', 120]], ['dosai', 'sada dosa', 'plain dosai']],
  ['khichdi', 'Khichdi (rice + moong dal)', 'Grains & breads', 'g', 125, 4.5, 21.0, 2.5, 2.0,
    [['1 katori (bowl)', 200]], ['khichri', 'kitchari', 'dal khichdi', 'moong dal khichdi']],

  // ── Dals & legumes (cooked) ─────────────────────────────────────────────
  ['dal-cooked', 'Dal, cooked (plain, medium consistency)', 'Dals & legumes', 'g', 104, 6.0, 16.0, 1.8, 4.0,
    [['1 katori (bowl)', 150]], ['dal', 'daal', 'dhal', 'toor dal', 'arhar dal', 'lentil curry', 'plain dal']],
  ['dal-tadka', 'Dal tadka / dal fry', 'Dals & legumes', 'g', 130, 6.0, 15.0, 5.0, 4.0,
    [['1 katori (bowl)', 150]], ['dal fry', 'tadka dal', 'yellow dal']],
  ['moong-cooked', 'Moong (mung beans), boiled', 'Dals & legumes', 'g', 105, 7.0, 19.2, 0.4, 7.6,
    [['1 katori (bowl)', 150]], ['mung', 'green gram', 'moong dal boiled']],
  ['masoor-cooked', 'Masoor (lentils), boiled', 'Dals & legumes', 'g', 116, 9.0, 20.1, 0.4, 7.9,
    [['1 katori (bowl)', 150]], ['lentils', 'red lentil', 'masoor dal']],
  ['chickpeas-cooked', 'Chickpeas (chana), boiled', 'Dals & legumes', 'g', 164, 8.9, 27.4, 2.6, 7.6,
    [['1 katori (bowl)', 150], ['1 cup', 164]], ['chana', 'kabuli chana', 'garbanzo', 'chole boiled']],
  ['chole', 'Chole / chana masala', 'Dals & legumes', 'g', 150, 6.5, 18.0, 6.0, 5.5,
    [['1 katori (bowl)', 150]], ['chana masala', 'chickpea curry', 'chhole', 'pindi chole']],
  ['rajma-cooked', 'Rajma (kidney beans), boiled', 'Dals & legumes', 'g', 127, 8.7, 22.8, 0.5, 6.4,
    [['1 katori (bowl)', 150]], ['kidney beans', 'rajmah']],
  ['sprouts-moong', 'Moong sprouts, raw', 'Dals & legumes', 'g', 30, 3.0, 5.9, 0.2, 1.8,
    [['1 cup', 104]], ['sprouts', 'bean sprouts', 'ankurit moong']],
  ['soya-chunks-dry', 'Soya chunks (dry)', 'Dals & legumes', 'g', 345, 52.0, 33.0, 0.5, 13.0,
    [['1 serving', 30]], ['nutrela', 'soy chunks', 'meal maker', 'soya badi']],
  ['tofu-firm', 'Tofu, firm', 'Dals & legumes', 'g', 144, 17.3, 2.8, 8.7, 2.3,
    [['1 serving', 100]], ['beancurd', 'soy paneer']],
  ['roasted-chana', 'Roasted chana (bhuna chana)', 'Dals & legumes', 'g', 365, 22.0, 58.0, 5.0, 17.0,
    [['1 handful', 30]], ['bhuna chana', 'roasted gram', 'phutana']],

  // ── Dairy ───────────────────────────────────────────────────────────────
  ['milk-whole', 'Milk, whole / full cream', 'Dairy', 'ml', 61, 3.2, 4.8, 3.3, 0,
    [['1 glass', 250], ['1 cup', 240]], ['doodh', 'full cream milk', 'cow milk']],
  ['milk-toned', 'Milk, toned (3% fat)', 'Dairy', 'ml', 58, 3.1, 4.7, 3.0, 0,
    [['1 glass', 250], ['1 cup', 240]], ['milk', 'doodh', 'toned milk']],
  ['milk-double-toned', 'Milk, double toned (1.5% fat)', 'Dairy', 'ml', 45, 3.2, 4.7, 1.5, 0,
    [['1 glass', 250], ['1 cup', 240]], ['doodh', 'low fat milk']],
  ['milk-skimmed', 'Milk, skimmed', 'Dairy', 'ml', 34, 3.4, 5.0, 0.1, 0,
    [['1 glass', 250], ['1 cup', 240]], ['skim milk', 'fat free milk']],
  ['milk-buffalo', 'Milk, buffalo', 'Dairy', 'ml', 97, 3.8, 5.2, 6.9, 0,
    [['1 glass', 250]], ['bhains doodh']],
  ['curd', 'Curd / dahi (plain, whole milk)', 'Dairy', 'g', 61, 3.5, 4.7, 3.3, 0,
    [['1 katori (bowl)', 150], ['1 cup', 245]], ['dahi', 'yogurt', 'yoghurt', 'plain curd', 'thayir']],
  ['greek-yogurt', 'Greek yogurt, plain, non-fat', 'Dairy', 'g', 59, 10.2, 3.6, 0.4, 0,
    [['1 cup', 170]], ['hung curd', 'greek yoghurt']],
  ['paneer', 'Paneer (full fat)', 'Dairy', 'g', 272, 18.3, 3.1, 20.8, 0,
    [['1 cube (small piece)', 25], ['1 serving', 100]], ['cottage cheese', 'panir', 'raw paneer']],
  ['cheese-slice', 'Cheese, processed slice', 'Dairy', 'g', 309, 20.0, 1.0, 25.0, 0,
    [['1 slice', 20]], ['cheese', 'amul cheese']],
  ['butter', 'Butter', 'Fats & oils', 'g', 717, 0.9, 0.1, 81.1, 0,
    [['1 tsp', 5], ['1 tbsp', 14]], ['makhan', 'amul butter']],
  ['ghee', 'Ghee', 'Fats & oils', 'g', 900, 0, 0, 99.8, 0,
    [['1 tsp', 5], ['1 tbsp', 13]], ['clarified butter', 'desi ghee']],
  ['oil-vegetable', 'Cooking oil (any vegetable oil)', 'Fats & oils', 'g', 884, 0, 0, 100, 0,
    [['1 tsp', 4.5], ['1 tbsp', 13.6]], ['oil', 'tel', 'sunflower oil', 'mustard oil', 'olive oil', 'groundnut oil', 'coconut oil']],
  ['lassi-sweet', 'Lassi, sweet', 'Beverages', 'ml', 75, 2.5, 11.0, 2.3, 0,
    [['1 glass', 250]], ['meethi lassi', 'sweet lassi']],
  ['chaas', 'Chaas / buttermilk (salted)', 'Beverages', 'ml', 25, 1.4, 2.0, 1.2, 0,
    [['1 glass', 250]], ['buttermilk', 'mattha', 'majjige', 'salted lassi']],
  ['whey-protein', 'Whey protein powder (typical)', 'Dairy', 'g', 398, 78.0, 8.0, 6.0, 0,
    [['1 scoop', 30]], ['protein powder', 'whey', 'protein shake powder']],

  // ── Eggs ────────────────────────────────────────────────────────────────
  ['egg-boiled', 'Egg, boiled (whole)', 'Eggs', 'g', 155, 12.6, 1.1, 10.6, 0,
    [['1 large egg', 50], ['1 medium egg', 44]], ['anda', 'ubla anda', 'boiled egg', 'hard boiled egg', 'egg']],
  ['egg-raw', 'Egg, whole, raw', 'Eggs', 'g', 143, 12.6, 0.7, 9.5, 0,
    [['1 large egg', 50], ['1 medium egg', 44]], ['raw egg']],
  ['egg-white', 'Egg white', 'Eggs', 'g', 52, 10.9, 0.7, 0.2, 0,
    [['1 egg white', 33]], ['anda safedi', 'egg whites']],
  ['egg-yolk', 'Egg yolk', 'Eggs', 'g', 322, 15.9, 3.6, 26.5, 0,
    [['1 yolk', 17]], []],
  ['omelette', 'Omelette (whole eggs, cooked with oil)', 'Eggs', 'g', 154, 10.6, 0.6, 11.7, 0,
    [['2-egg omelette', 120], ['1-egg omelette', 60]], ['omelet', 'omlet', 'anda omelette', 'masala omelette']],
  ['egg-fried', 'Egg, fried', 'Eggs', 'g', 196, 13.6, 0.8, 14.8, 0,
    [['1 fried egg', 46]], ['fried egg', 'bull eye', 'sunny side up']],

  // ── Meat & fish ─────────────────────────────────────────────────────────
  ['chicken-breast-cooked', 'Chicken breast, cooked (skinless)', 'Meat & fish', 'g', 165, 31.0, 0, 3.6, 0,
    [['1 piece (palm size)', 100], ['1 whole breast', 170]], ['grilled chicken', 'boiled chicken', 'chicken breast', 'murgh']],
  ['chicken-breast-raw', 'Chicken breast, raw (skinless)', 'Meat & fish', 'g', 120, 22.5, 0, 2.6, 0,
    [['1 whole breast', 200]], ['raw chicken']],
  ['chicken-thigh-cooked', 'Chicken thigh, cooked (skinless)', 'Meat & fish', 'g', 179, 24.8, 0, 8.2, 0,
    [['1 thigh', 75]], ['chicken leg']],
  ['mutton-cooked', 'Mutton / goat meat, cooked', 'Meat & fish', 'g', 143, 27.1, 0, 3.0, 0,
    [['1 serving', 100]], ['goat', 'lamb', 'gosht', 'bakra']],
  ['mutton-curry', 'Mutton curry', 'Meat & fish', 'g', 150, 12.0, 4.0, 9.5, 0.8,
    [['1 katori (bowl)', 150]], ['gosht curry', 'mutton masala', 'lamb curry']],
  ['fish-lean-cooked', 'Fish, lean, cooked (rohu / tilapia type)', 'Meat & fish', 'g', 128, 26.2, 0, 2.7, 0,
    [['1 piece', 100]], ['machli', 'machhi', 'fish', 'rohu', 'tilapia', 'pomfret']],
  ['salmon-cooked', 'Salmon, cooked', 'Meat & fish', 'g', 206, 22.1, 0, 12.4, 0,
    [['1 fillet', 150]], []],
  ['tuna-canned', 'Tuna, canned in water', 'Meat & fish', 'g', 116, 25.5, 0, 0.8, 0,
    [['1 can (drained)', 140]], []],
  ['prawns-cooked', 'Prawns / shrimp, cooked', 'Meat & fish', 'g', 99, 24.0, 0.2, 0.3, 0,
    [['1 serving', 100]], ['jhinga', 'shrimp', 'prawn']],

  // ── Vegetables ──────────────────────────────────────────────────────────
  ['potato-boiled', 'Potato, boiled', 'Vegetables', 'g', 87, 1.9, 20.1, 0.1, 1.8,
    [['1 medium potato', 150]], ['aloo', 'alu', 'boiled potato']],
  ['sweet-potato-boiled', 'Sweet potato, boiled', 'Vegetables', 'g', 76, 1.4, 17.7, 0.1, 2.5,
    [['1 medium', 150]], ['shakarkandi', 'shakarkand']],
  ['onion', 'Onion, raw', 'Vegetables', 'g', 40, 1.1, 9.3, 0.1, 1.7,
    [['1 medium onion', 110]], ['pyaz', 'pyaaz', 'kanda']],
  ['tomato', 'Tomato, raw', 'Vegetables', 'g', 18, 0.9, 3.9, 0.2, 1.2,
    [['1 medium tomato', 120]], ['tamatar']],
  ['cucumber', 'Cucumber, raw', 'Vegetables', 'g', 15, 0.7, 3.6, 0.1, 0.5,
    [['1 medium', 200], ['1 cup sliced', 120]], ['kheera', 'kakdi']],
  ['carrot', 'Carrot, raw', 'Vegetables', 'g', 41, 0.9, 9.6, 0.2, 2.8,
    [['1 medium carrot', 60]], ['gajar']],
  ['spinach', 'Spinach, raw', 'Vegetables', 'g', 23, 2.9, 3.6, 0.4, 2.2,
    [['1 cup', 30]], ['palak']],
  ['broccoli', 'Broccoli, raw', 'Vegetables', 'g', 34, 2.8, 6.6, 0.4, 2.6,
    [['1 cup chopped', 91]], []],
  ['green-peas-cooked', 'Green peas, cooked', 'Vegetables', 'g', 84, 5.4, 15.6, 0.2, 5.5,
    [['1 katori (bowl)', 100]], ['matar', 'mutter', 'peas']],
  ['sweet-corn-cooked', 'Sweet corn, cooked', 'Vegetables', 'g', 96, 3.4, 21.0, 1.5, 2.4,
    [['1 cup', 145], ['1 cob', 100]], ['bhutta', 'corn', 'makka']],

  // ── Fruits ──────────────────────────────────────────────────────────────
  ['banana', 'Banana', 'Fruits', 'g', 89, 1.1, 22.8, 0.3, 2.6,
    [['1 medium banana', 118], ['1 small banana', 101], ['1 large banana', 136]], ['kela', 'kele']],
  ['apple', 'Apple', 'Fruits', 'g', 52, 0.3, 13.8, 0.2, 2.4,
    [['1 medium apple', 182]], ['seb', 'saeb']],
  ['mango', 'Mango', 'Fruits', 'g', 60, 0.8, 15.0, 0.4, 1.6,
    [['1 cup sliced', 165], ['1 medium mango (edible part)', 200]], ['aam', 'amba']],
  ['orange', 'Orange', 'Fruits', 'g', 47, 0.9, 11.8, 0.1, 2.4,
    [['1 medium orange', 131]], ['santra', 'narangi', 'mosambi']],
  ['papaya', 'Papaya', 'Fruits', 'g', 43, 0.5, 10.8, 0.3, 1.7,
    [['1 cup cubes', 145]], ['papita']],
  ['grapes', 'Grapes', 'Fruits', 'g', 69, 0.7, 18.1, 0.2, 0.9,
    [['1 cup', 151]], ['angoor']],
  ['watermelon', 'Watermelon', 'Fruits', 'g', 30, 0.6, 7.6, 0.2, 0.4,
    [['1 cup diced', 152]], ['tarbooz', 'tarbuj']],
  ['guava', 'Guava', 'Fruits', 'g', 68, 2.6, 14.3, 1.0, 5.4,
    [['1 guava', 55]], ['amrood', 'amrud', 'peru']],
  ['pomegranate', 'Pomegranate (arils)', 'Fruits', 'g', 83, 1.7, 18.7, 1.2, 4.0,
    [['1/2 cup arils', 87]], ['anar']],
  ['pineapple', 'Pineapple', 'Fruits', 'g', 50, 0.5, 13.1, 0.1, 1.4,
    [['1 cup chunks', 165]], ['ananas']],
  ['pear', 'Pear', 'Fruits', 'g', 57, 0.4, 15.2, 0.1, 3.1,
    [['1 medium pear', 178]], ['nashpati']],
  ['strawberries', 'Strawberries', 'Fruits', 'g', 32, 0.7, 7.7, 0.3, 2.0,
    [['1 cup', 152]], ['strawberry']],
  ['dates-dried', 'Dates, dried', 'Fruits', 'g', 282, 2.5, 75.0, 0.4, 8.0,
    [['1 date', 8], ['1 medjool date', 24]], ['khajur', 'khajoor']],

  // ── Nuts & seeds ────────────────────────────────────────────────────────
  ['almonds', 'Almonds', 'Nuts & seeds', 'g', 579, 21.2, 21.6, 49.9, 12.5,
    [['10 almonds', 12], ['1 handful', 28]], ['badam']],
  ['peanuts-roasted', 'Peanuts, roasted', 'Nuts & seeds', 'g', 587, 24.4, 21.3, 49.7, 8.0,
    [['1 handful', 28], ['1 tbsp', 9]], ['moongfali', 'mungfali', 'groundnut', 'shengdana']],
  ['peanut-butter', 'Peanut butter', 'Nuts & seeds', 'g', 588, 25.0, 20.0, 50.0, 6.0,
    [['1 tbsp', 16]], []],
  ['cashews', 'Cashews', 'Nuts & seeds', 'g', 553, 18.2, 30.2, 43.9, 3.3,
    [['10 cashews', 15], ['1 handful', 28]], ['kaju']],
  ['walnuts', 'Walnuts', 'Nuts & seeds', 'g', 654, 15.2, 13.7, 65.2, 6.7,
    [['1 handful', 28]], ['akhrot']],
  ['chia-seeds', 'Chia seeds', 'Nuts & seeds', 'g', 486, 16.5, 42.1, 30.7, 34.4,
    [['1 tbsp', 12]], []],
  ['flax-seeds', 'Flax seeds', 'Nuts & seeds', 'g', 534, 18.3, 28.9, 42.2, 27.3,
    [['1 tbsp', 10]], ['alsi', 'linseed']],
  ['makhana', 'Makhana (fox nuts), roasted', 'Nuts & seeds', 'g', 347, 9.7, 76.9, 0.1, 14.5,
    [['1 cup', 15]], ['fox nut', 'lotus seed', 'phool makhana']],

  // ── Sweeteners ──────────────────────────────────────────────────────────
  ['sugar', 'Sugar', 'Sweets & desserts', 'g', 387, 0, 100, 0, 0,
    [['1 tsp', 4], ['1 tbsp', 12.5]], ['cheeni', 'chini', 'shakkar']],
  ['jaggery', 'Jaggery', 'Sweets & desserts', 'g', 383, 0.4, 98.0, 0.1, 0,
    [['1 tsp', 5], ['1 small piece', 10]], ['gud', 'gur', 'vellam']],
  ['honey', 'Honey', 'Sweets & desserts', 'g', 304, 0.3, 82.4, 0, 0.2,
    [['1 tsp', 7], ['1 tbsp', 21]], ['shahad', 'madhu']],

  // ── Common Indian snacks & sweets ───────────────────────────────────────
  ['samosa', 'Samosa (potato)', 'Snacks & fried foods', 'g', 300, 5.0, 32.0, 17.0, 3.0,
    [['1 samosa', 70]], ['aloo samosa', 'samosas']],
  ['pakora', 'Pakora / bhaji (onion or mixed veg)', 'Snacks & fried foods', 'g', 276, 7.0, 26.0, 16.0, 4.0,
    [['1 piece', 20]], ['pakoda', 'bhajji', 'bhajiya', 'onion bhaji', 'pakore']],
  ['poori', 'Poori', 'Grains & breads', 'g', 343, 7.0, 44.0, 15.5, 3.5,
    [['1 poori', 25]], ['puri', 'poori bhaji']],
  ['bhatura', 'Bhatura', 'Grains & breads', 'g', 332, 8.0, 48.0, 12.0, 2.0,
    [['1 bhatura', 80]], ['bhature', 'chole bhature']],
  ['medu-vada', 'Medu vada', 'Snacks & fried foods', 'g', 304, 10.0, 30.0, 16.0, 4.0,
    [['1 vada', 50]], ['vada', 'wada', 'vadai', 'urad vada']],
  ['kachori', 'Kachori', 'Snacks & fried foods', 'g', 401, 8.0, 45.0, 21.0, 4.0,
    [['1 kachori', 60]], ['kachauri', 'khasta kachori']],
  ['vada-pav', 'Vada pav', 'Snacks & fried foods', 'g', 195, 5.0, 28.0, 7.0, 2.5,
    [['1 vada pav', 150]], ['wada pav', 'vadapav']],
  ['dhokla', 'Dhokla', 'Snacks & fried foods', 'g', 161, 6.5, 23.0, 4.8, 2.0,
    [['1 piece', 30]], ['khaman', 'khaman dhokla']],
  ['gulab-jamun', 'Gulab jamun (with syrup)', 'Sweets & desserts', 'g', 377, 4.0, 52.0, 17.0, 0.3,
    [['1 piece', 40]], ['gulabjamun']],
  ['jalebi', 'Jalebi', 'Sweets & desserts', 'g', 400, 2.0, 62.0, 16.0, 0.5,
    [['1 piece', 25]], ['jilebi', 'imarti']],
  ['biscuit-glucose', 'Biscuit, glucose / Marie type', 'Snacks & fried foods', 'g', 449, 7.0, 76.0, 13.0, 1.5,
    [['1 biscuit', 7]], ['parle g', 'marie biscuit', 'cookies']],
  ['potato-chips', 'Potato chips', 'Snacks & fried foods', 'g', 555, 7.0, 53.0, 35.0, 4.4,
    [['1 small pack', 30]], ['wafers', 'crisps', 'lays']],

  // ── Beverages ───────────────────────────────────────────────────────────
  ['chai-milk-sugar', 'Tea (chai) with milk and sugar', 'Beverages', 'ml', 45, 1.2, 7.0, 1.3, 0,
    [['1 cup', 150]], ['chai', 'masala chai', 'tea', 'cutting chai']],
  ['chai-no-sugar', 'Tea with milk, no sugar', 'Beverages', 'ml', 20, 1.1, 1.6, 1.1, 0,
    [['1 cup', 150]], ['chai without sugar', 'tea no sugar']],
  ['coffee-milk-sugar', 'Coffee with milk and sugar', 'Beverages', 'ml', 50, 1.6, 6.5, 1.9, 0,
    [['1 cup', 150]], ['filter coffee', 'kaapi', 'milk coffee']],
  ['coffee-black', 'Coffee, black (no sugar)', 'Beverages', 'ml', 1, 0.1, 0, 0, 0,
    [['1 cup', 240]], ['black coffee', 'americano', 'espresso']],
  ['cola', 'Cola / soft drink', 'Beverages', 'ml', 42, 0, 10.6, 0, 0,
    [['1 can', 330], ['1 glass', 250]], ['coke', 'pepsi', 'soda', 'cold drink', 'thums up']],
  ['orange-juice', 'Orange juice', 'Beverages', 'ml', 45, 0.7, 10.4, 0.2, 0.2,
    [['1 glass', 250]], ['juice', 'santra juice']],
  ['coconut-water', 'Coconut water', 'Beverages', 'ml', 19, 0.7, 3.7, 0.2, 1.1,
    [['1 coconut', 250]], ['nariyal pani', 'tender coconut']],
];
